package kyu7;

import java.util.Arrays;
import java.util.Scanner;

public class SequenceSum {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = Integer.valueOf(sc.nextLine());
        sc.close();
        System.out.println(Arrays.toString(sumOfN(n)));
    }

    public static int[] sumOfN(int n) {
        int[] temp = new int[Math.abs(n) + 1];
        for (int i = 0; i < temp.length; i++) {
            if (n > 0) {
                temp[i] = i;
            } else {
                temp[i] = -i;
            }
        }
        int[] ans = new int[temp.length];
        for (int i = 0; i < ans.length; i++) {
            if (i == 0) {
                ans[i] = temp[i];
            } else {
                ans[i] = ans[i - 1] + temp[i];
            }
        }
        return ans; // Generated by die roll; guaranteed to be random
    }
}
